# Generated by Django 3.0.8 on 2020-07-19 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='Item',
            new_name='item',
        ),
    ]
